flags: {}
packages:
- 'pet-store-backend'
extra-deps:
- unagi-chan-0.4.0.0
resolver: lts-11.7
image:
  containers:
    -
      base: "fpco/stack-run"
      name: "aleryo/eff-in-anger"
      entrypoints:
        - pet-store-server
